### ISSUE TITLE
designer won't start on rcloud.social

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud.rcap#118]
I attempted to install rcloud.rcap on https://rcloud.social because it's open source now (yay!) and @emdodwell may have some cool demos.

It looks like the package installed properly & it's the exact same package I installed internally & RCAP Designer does appear in the Advanced menu.

Yet nothing happens when I run it. 😦 

Please investigate.

**Comment by gordonwoodhull** [comment]
If you want to try uploading and installing it yourself, this notebook shows how I installed it:
https://rcloud.social/edit.html?notebook=2c83088667610c4df5eef3e34bb32831

And of course, you need to Enable Extensions rcloud.rcap in order to test.

**Comment by gaborcsardi** [comment]
A simple way to install releases from GitHub:
```r
devtools::install_url("https://github.com/att/rcloud.rcap/releases/download/0.3.5/rcloud.rcap_0.3.5.tar.gz")
```

The designer indeed does not load, because `shared.R` does not work, at least for `rcloud.rcap`. Try https://rcloud.social/shared.R/rcloud.rcap/js/designer.js

I guess this is because each Rserve backend is in a separate Docker (?) container, and the container that runs `shared.R` does not have `rcloud.rcap` installed. So if you add it to the container image, it should be fine I believe.

**Comment by gordonwoodhull** [comment]
Got it. So it was my install method which was insufficient, since scripts do not necessarily run on the same machine as compute sessions. 

Thanks for the devtools tip!
