### ISSUE TITLE
Visual indicator if a control is about to update

### ISSUE THREAD

**Issue by paulinshek** [att/rcloud.rcap#121]
This would be useful in large and slow dashboards: when a user makes a change to a form, or presses a button it would be nice to see which controls are about to update.

**Comment by shaneporter** [comment]
Sounds like a good idea. I guess I'm right in saying that dependency graph doesn't change after it is derived at runtime. If so, an ocap returns this to the client side at runtime (once and once only). Afterwards, this is referred to following a change, and the message displayed if appropriate.

**Comment by gaborcsardi** [comment]
I don't know, maybe I would just call back to the frontend with the ids of the controls about to be refreshed. To allow the backend not refreshing some control.

It is somewhat tricky because of the timing. It might happen that we get the refreshed control before putting out the indicator. We can assign an ID to each refresh, and include this ID both in the initial indicator ocap and the control refresh ocap. Then we know if a refresh event has already arrived when we are about to put out the indicator.

**Comment by robert-a** [comment]
I think that the way to handle this is to create a "Progress" widget that could be placed on the page (or on multiple pages). The widget would normally display some optional text (like the Text widget). The text could be different in each occurrence of the widget. When an update request is sent to the back-end it would change all the Progress widgets to the RCloud spinner (or other selected progress icon). When the back-end has finished the DAG, it would send a message to the front-end to return the Progress widgets to their text.
